name: CI Workflow

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  buildAndTest:
    name: Build, Test, and Package
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: hri-dev1-wdc-kube

    steps:
      - name: Set branch name
        uses: nelonoel/branch-name@v1.0.1

      - uses: actions/checkout@v2

      - name: Set up adoptopenjdk8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          ./gradlew clean build

      - name: Gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --stacktrace
